// Visualize this code using Mermaid JS

// Practice solution
---
title: Car rental company that keeps track of cars, renter, and renter renting cars
---
classDiagram
    RentalCompany "1" o-- "1..*" Car
    RentalCompany "1..*" *-- "0..*" RenterRentingCar
    Renter <|-- RenterRentingCar
    RenterRentingCar "1" o-- "1..*" Car
    class RentalCompany
    class Car
    class Renter
    class RenterRentingCar

// Actual solution
---
title: Car rental company that keeps track of cars, renter, and renter renting cars
---
classDiagram
    RentalCompany "1" o-- "0..*" Car
    RentalCompany "1" o-- "0..*" Rental
    RentalCompany "1" o-- "0..*" Renter
    Rental "1" o-- "1" Car
    Rental "0..*" o-- "1" Renter
    class RentalCompany
    class Car
    class Rental
    class Renter 

